"use client";

import { useState, type ReactNode } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Bell, BedDouble, Building2, CalendarCheck2, ChevronDown, CircleDollarSign, ClipboardCheck, DoorOpen, Ellipsis, LayoutDashboard, LogOut, Menu, Percent, Search, Settings, ShieldCheck, Sparkles, Users, X } from "lucide-react";
import { BrandMark } from "@/components/brand-mark";
import { SignOutButton } from "@/components/sign-out-button";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { roleLabels, type AppRole } from "@/lib/auth";
import { dashboardBookings, dashboardRevenue, dashboardStats, type DashboardData } from "@/lib/data";

const navItems = [
  { label: "ภาพรวม", adminLabel: "ภาพรวมระบบ", href: "/dashboard", icon: LayoutDashboard, roles: ["manager", "admin"] as AppRole[] },
  { label: "การจอง", href: "/dashboard/bookings", icon: CalendarCheck2, roles: ["receptionist", "manager"] as AppRole[] },
  { label: "เช็กอิน/เช็กเอาต์", href: "/dashboard/front-desk", icon: DoorOpen, roles: ["receptionist", "manager"] as AppRole[] },
  { label: "ห้องพัก", href: "/dashboard/rooms", icon: BedDouble, roles: ["manager"] as AppRole[] },
  { label: "ลูกค้า", href: "/dashboard/customers", icon: Users, roles: ["receptionist", "manager"] as AppRole[] },
  { label: "รายงาน", href: "/dashboard/reports", icon: CircleDollarSign, roles: ["manager"] as AppRole[] },
  { label: "ผู้ใช้และสิทธิ์", href: "/dashboard/users", icon: Users, roles: ["admin"] as AppRole[] },
  { label: "ตั้งค่าโรงแรม", href: "/dashboard/settings", icon: Settings, roles: ["manager"] as AppRole[] },
];

const demoDashboardData: DashboardData = { stats: dashboardStats, bookings: dashboardBookings, revenue: dashboardRevenue, bookingBadge: 12, todayLabel: "จันทร์ 17 สิงหาคม 2569", roomSummary: { available: 10, total: 48 } };

type DashboardShellMeta = Pick<DashboardData, "bookingBadge" | "todayLabel">;

export function DashboardShell({ profile = { fullName: "ศตายุ เสริฐศรี", role: "manager" as AppRole }, data, shellMeta, children }: { profile?: { fullName: string; role: AppRole }; data?: DashboardData; shellMeta?: DashboardShellMeta; children?: ReactNode }) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const pathname = usePathname();
  const viewData: DashboardData = { ...demoDashboardData, ...data, ...shellMeta };
  const visibleNavItems = navItems.filter((item) => item.roles.includes(profile.role));
  const activeItem = visibleNavItems.find((item) => item.href === "/dashboard" ? pathname === item.href : pathname.startsWith(item.href)) ?? visibleNavItems[0];
  const active = activeItem?.adminLabel && profile.role === "admin" ? activeItem.adminLabel : activeItem?.label ?? "ภาพรวม";
  const initials = profile.fullName.slice(0, 2);

  return <div className="flex min-h-screen">
    <aside className={sidebarOpen ? "fixed inset-y-0 left-0 z-50 flex w-72 flex-col bg-brand-900 p-5 shadow-2xl lg:static lg:flex" : "hidden w-72 shrink-0 flex-col bg-brand-900 p-5 lg:flex"}>
      <div className="flex items-center justify-between"><Link href="/"><BrandMark inverse /></Link><button type="button" className="text-white/60 lg:hidden" onClick={() => setSidebarOpen(false)}><X className="size-5" /></button></div>
      <div className="mt-10 rounded-2xl border border-white/10 bg-white/5 p-3"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-brand-300 text-sm font-black text-brand-900">{initials}</span><span className="min-w-0"><strong className="block truncate text-xs text-white">{profile.fullName}</strong><small className="text-[10px] text-white/45">{roleLabels[profile.role]}</small></span><ChevronDown className="ml-auto size-3.5 text-white/40" /></div></div>
      <nav className="mt-8 space-y-1">{visibleNavItems.map((item) => { const label = item.adminLabel && profile.role === "admin" ? item.adminLabel : item.label; const Icon = item.icon; return <Link href={item.href} key={item.href} onClick={() => setSidebarOpen(false)} className={active === label ? "flex w-full items-center gap-3 rounded-xl bg-white/12 px-3 py-3 text-left text-sm font-bold text-white" : "flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-medium text-white/55 transition hover:bg-white/7 hover:text-white"}><Icon className="size-4" />{label}{item.label === "การจอง" && viewData.bookingBadge > 0 && <span className="ml-auto rounded-full bg-coral-500 px-2 py-0.5 text-[10px] font-bold text-white">{viewData.bookingBadge}</span>}</Link>; })}</nav>
      <div className="mt-auto space-y-1"><Link href="/" className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium text-white/55 hover:bg-white/7 hover:text-white"><LogOut className="size-4" />กลับหน้าเว็บไซต์</Link><SignOutButton variant="ghost" className="w-full justify-start text-white/55 hover:bg-white/7 hover:text-white" /></div>
    </aside>
    {sidebarOpen && <button type="button" className="fixed inset-0 z-40 bg-brand-900/30 lg:hidden" onClick={() => setSidebarOpen(false)} aria-label="ปิดเมนู" />}
    <div className="min-w-0 flex-1">
      <header className="flex h-[76px] items-center justify-between border-b bg-white/90 px-5 backdrop-blur lg:px-8"><div className="flex items-center gap-3"><button type="button" className="text-muted-ink lg:hidden" onClick={() => setSidebarOpen(true)}><Menu className="size-5" /></button><div><p className="text-xs text-muted-ink">{viewData.todayLabel}</p><h1 className="mt-0.5 text-base font-black">{active}</h1></div></div><div className="flex items-center gap-2"><button type="button" className="hidden size-10 place-items-center rounded-xl border bg-white text-muted-ink sm:grid"><Search className="size-4" /></button><button type="button" className="relative grid size-10 place-items-center rounded-xl border bg-white text-muted-ink"><Bell className="size-4" /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-coral-500" /></button><DashboardProfileMenu profile={profile} initials={initials} /></div></header>
      <div className="mx-auto max-w-[1440px] p-5 lg:p-8">{children ?? <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 inline-flex items-center gap-1.5 rounded-full bg-brand-100 px-2.5 py-1 text-[10px] font-bold text-brand-800"><Sparkles className="size-3" /> LUMA OS · ระบบจัดการโรงแรม</div><h2 className="text-2xl font-black tracking-tight lg:text-3xl">สวัสดีครับ {profile.fullName} <span className="text-brand-600">👋</span></h2><p className="mt-2 text-sm text-muted-ink">นี่คือภาพรวมของโรงแรมคุณในวันนี้ · {roleLabels[profile.role]}</p></div><Button variant="outline" size="sm"><ClipboardCheck className="size-4" /> รายงานประจำเดือน <ChevronDown className="size-3.5" /></Button></div>}
      {children ? null : <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{viewData.stats.map((stat) => <StatCard key={stat.label} {...stat} />)}</section><div className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><RevenueChart revenue={viewData.revenue} /><OccupancyCard available={viewData.roomSummary.available} total={viewData.roomSummary.total} /></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><BookingsTable bookings={viewData.bookings} /><QuickActions /></div></>}
      </div>
    </div>
  </div>;
}

function StatCard({ label, value, change, caption, accent }: { label: string; value: string; change: string; caption: string; accent: string }) { const colors: Record<string, string> = { brand: "bg-brand-100 text-brand-700", gold: "bg-[#fff4d8] text-[#9a6b08]", coral: "bg-coral-50 text-coral-600", purple: "bg-[#f1edff] text-[#6a52b3]" }; const icons: Record<string, React.ReactNode> = { brand: <CircleDollarSign className="size-4" />, gold: <Percent className="size-4" />, coral: <CalendarCheck2 className="size-4" />, purple: <ShieldCheck className="size-4" /> }; return <div className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><span className={`grid size-9 place-items-center rounded-xl ${colors[accent]}`}>{icons[accent]}</span><span className="rounded-full bg-[#e7f7ed] px-2 py-1 text-[10px] font-bold text-[#177245]">{change}</span></div><p className="mt-5 text-xs font-medium text-muted-ink">{label}</p><p className="mt-1 text-2xl font-black tracking-tight">{value}</p><p className="mt-1 text-[11px] text-muted-ink">{caption}</p></div>; }

function RevenueChart({ revenue }: { revenue: DashboardData["revenue"] }) { const maxAmount = Math.max(...revenue.map((item) => item.amount), 1); const total = revenue.reduce((sum, item) => sum + item.amount, 0); return <section className="rounded-2xl border bg-white p-5 lg:p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-muted-ink">รายได้รวม 12 เดือนล่าสุด</p><p className="mt-1 text-xl font-black">฿{total.toLocaleString("th-TH")} <span className="text-xs font-bold text-muted-ink">จากการจองที่ยังไม่ยกเลิก</span></p></div><span className="rounded-lg border bg-white px-2 py-1.5 text-xs font-semibold text-muted-ink">ข้อมูลจริง</span></div><div className="mt-8 flex h-48 items-end gap-2 border-b border-l px-3 pb-0 pt-4 sm:gap-4">{revenue.map((item, index) => <div key={`${item.label}-${index}`} className="group flex h-full flex-1 items-end" title={`${item.label}: ฿${item.amount.toLocaleString("th-TH")}`}><div className={index === revenue.length - 1 ? "relative w-full rounded-t-md bg-brand-600 transition group-hover:bg-brand-700" : "relative w-full rounded-t-md bg-brand-100 transition group-hover:bg-brand-300"} style={{ height: `${Math.max((item.amount / maxAmount) * 100, item.amount ? 4 : 0)}%` }} /></div>)}</div><div className="mt-3 flex justify-between pl-3 text-[10px] text-muted-ink">{revenue.map((item, index) => <span key={`${item.label}-label-${index}`}>{item.label}</span>)}</div></section>; }

function OccupancyCard({ available, total }: DashboardData["roomSummary"]) { const occupied = Math.max(total - available, 0); const occupancy = total ? Math.round((occupied / total) * 1000) / 10 : 0; return <section className="rounded-2xl bg-brand-900 p-5 text-white lg:p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-white/55">อัตราการเข้าพักวันนี้</p><p className="mt-1 text-3xl font-black">{occupancy}%</p></div><span className="grid size-10 place-items-center rounded-xl bg-white/10"><Building2 className="size-5 text-brand-300" /></span></div><div className="mt-7 flex items-end gap-1"><div className="h-24 w-full rounded-t-lg bg-white/10" /><div className="h-32 w-full rounded-t-lg bg-white/15" /><div className="h-28 w-full rounded-t-lg bg-brand-400" /><div className="h-40 w-full rounded-t-lg bg-brand-300" /><div className="h-36 w-full rounded-t-lg bg-brand-400" /><div className="h-44 w-full rounded-t-lg bg-white/80" /><div className="h-36 w-full rounded-t-lg bg-brand-300" /></div><div className="mt-4 flex items-center justify-between border-t border-white/10 pt-4 text-xs"><span className="text-white/55">ห้องว่าง {available} ห้อง</span><span className="font-bold text-brand-200">ห้องทั้งหมด {total} ห้อง</span></div></section>; }

function BookingsTable({ bookings }: { bookings: DashboardData["bookings"] }) { return <section className="overflow-hidden rounded-2xl border bg-white"><div className="flex items-center justify-between border-b px-5 py-4"><div><h3 className="text-sm font-bold">การจองล่าสุด</h3><p className="mt-1 text-[11px] text-muted-ink">รายการที่ต้องติดตามวันนี้</p></div><Button variant="ghost" size="sm">ดูทั้งหมด <ChevronDown className="size-3.5 -rotate-90" /></Button></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead><tr className="border-b bg-[#fbfcfb] text-[10px] font-bold uppercase tracking-wider text-muted-ink"><th className="px-5 py-3">หมายเลข</th><th className="px-5 py-3">ผู้เข้าพัก</th><th className="px-5 py-3">ห้องพัก</th><th className="px-5 py-3">วันที่</th><th className="px-5 py-3">สถานะ</th><th className="px-5 py-3 text-right">ยอดรวม</th></tr></thead><tbody>{bookings.map((booking) => <tr key={booking.id} className="border-b last:border-0"><td className="px-5 py-4 text-xs font-bold text-brand-700">{booking.id}</td><td className="px-5 py-4 text-xs font-semibold">{booking.guest}</td><td className="px-5 py-4 text-xs text-muted-ink">{booking.room}</td><td className="px-5 py-4 text-xs text-muted-ink">{booking.dates}</td><td className="px-5 py-4"><Badge variant={booking.status === "ยืนยันแล้ว" || booking.status === "ชำระแล้ว" ? "success" : booking.status === "รอชำระเงิน" ? "warning" : "default"}>{booking.status}</Badge></td><td className="px-5 py-4 text-right text-xs font-bold">฿{booking.amount.toLocaleString("th-TH")}</td></tr>)}</tbody></table></div></section>; }

function QuickActions() { const actions = [{ label: "เช็กอินผู้เข้าพัก", icon: DoorOpen, color: "bg-brand-50 text-brand-700" }, { label: "เพิ่มห้องพักใหม่", icon: BedDouble, color: "bg-[#fff4d8] text-[#9a6b08]" }, { label: "ดูปฏิทินห้องพัก", icon: CalendarCheck2, color: "bg-[#f1edff] text-[#6a52b3]" }, { label: "จัดการลูกค้า", icon: Users, color: "bg-coral-50 text-coral-600" }]; return <section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><h3 className="text-sm font-bold">ทางลัดการทำงาน</h3><Ellipsis className="size-4 text-muted-ink" /></div><div className="mt-4 grid gap-2">{actions.map(({ label, icon: Icon, color }) => <button key={label} type="button" className="flex items-center gap-3 rounded-xl border p-3 text-left transition hover:border-brand-300 hover:bg-brand-50"><span className={`grid size-9 place-items-center rounded-lg ${color}`}><Icon className="size-4" /></span><span className="flex-1 text-xs font-bold">{label}</span><ChevronDown className="size-3.5 -rotate-90 text-muted-ink" /></button>)}</div></section>; }

function DashboardProfileMenu({ profile, initials }: { profile: { fullName: string; role: AppRole }; initials: string }) {
  const [open, setOpen] = useState(false);
  return <div className="relative ml-2"><button type="button" aria-expanded={open} aria-haspopup="menu" onClick={() => setOpen((current) => !current)} className="flex items-center gap-2 rounded-xl border bg-white px-2 py-1.5 text-left transition hover:border-brand-300 hover:bg-brand-50"><span className="grid size-8 place-items-center rounded-full bg-brand-100 text-xs font-black text-brand-800">{initials}</span><span className="hidden max-w-[130px] truncate text-xs font-bold sm:block">{profile.fullName}</span><ChevronDown className={`size-3.5 text-muted-ink transition ${open ? "rotate-180" : ""}`} /></button>{open && <div role="menu" className="absolute right-0 top-12 z-50 w-64 rounded-2xl border bg-white p-2 shadow-[0_16px_40px_rgba(17,88,79,0.16)]"><div className="border-b px-3 py-3"><p className="truncate text-sm font-black">{profile.fullName}</p><p className="mt-1 text-xs text-muted-ink">{roleLabels[profile.role]}</p></div><Link role="menuitem" href="/account" onClick={() => setOpen(false)} className="mt-2 flex items-center rounded-xl px-3 py-2.5 text-xs font-bold text-muted-ink hover:bg-brand-50 hover:text-brand-800">ดูโปรไฟล์ของฉัน</Link><SignOutButton variant="ghost" className="mt-1 w-full justify-start rounded-xl px-3 py-2.5 text-xs font-bold text-coral-600 hover:bg-coral-50 hover:text-coral-600" /></div>}</div>;
}
